name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        haxe: [4.2.0, 3.4.7]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib install hxnodejs

      - name: Compile test code
        run: haxe -cp test-workflow -lib hxnodejs -main Main -js test-workflow.js
